CREATE TABLE CLIENT (
        id NUMBER,
        login VARCHAR2(100) NOT NULL,
        password VARCHAR2(100) NOT NULL,
        balance NUMBER(10, 2)
);

ALTER TABLE CLIENT ADD CONSTRAINT PK_CLIENT PRIMARY KEY (ID);
ALTER TABLE CLIENT ADD CONSTRAINT UK_CLIENT_LOGIN UNIQUE(LOGIN);

CREATE SEQUENCE SEQ_CLIENT START WITH 1;